namespace bombermanassetsSprites {
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const myImagesv1Xi = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const myImagespiqX0Z705Hpwt = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const myImagesBYqZ9O3T218cay$zof = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite15 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite17 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite18 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite19 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite20 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite21 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite22 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite23 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite24 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite25 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite26 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite27 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite28 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite29 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite30 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite31 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite32 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite33 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite34 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite35 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite36 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite37 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite38 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite39 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite40 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite41 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite42 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite43 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite44 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite45 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite46 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite47 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite48 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite49 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite50 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite51 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite52 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite53 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite54 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite55 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mySprite56 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const myTilestransparency16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    export const myTilestile1 = image.ofBuffer(hex``);

}
